# Generated by Django 2.0.3 on 2018-03-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
