# Generated by Django 2.0.3 on 2018-03-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='latest_review_uploaded_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='upload_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
