# Generated by Django 2.0.3 on 2018-04-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20180326_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
